export enum EnrollmentStatus {
  FULL_TIME = 'full-time',
  PART_TIME = 'part-time',
  ALL_TYPE = 'all-type',
}
export enum Location {
  REMOTE = 'remote',
  OFFICE = 'office',
}
export enum ExperienceLevel {
  INTERN = 'intern',
  JUNIOR = 'junior',
  MIDDLE = 'middle',
  SENIOR = 'senior',
  ALL_LEVEL = 'all-level',
}
export enum JobTag {
  BUSINESS = 'Business',
  FRONTEND = 'Front-end',
  FULLSTACK = 'Fullstack',
  ENGINEERING = 'Engineering',
  ANDROID = 'Android',
  BACKEND = 'Backend',
  ANALYTICS = 'Analytics',
  DESIGN = 'Design',
  TESTER = 'Tester',
  MANAGEMENT = 'Management',
  IOS = 'iOS',
  SITE_RELIABILITY = 'Site Reliability',
  DATA_ENGINEER = 'Data Engineer',
  AI_ENGINEER = 'AI/LLM Engineer',
  SECURITY_ENGINEER = 'Security Engineer',
  BIZ_DEVELOPMENT_EXECUTIVE = 'Business Development Executive',
  MARKETING_MANAGER = 'Marketing Manager - Software',
  MARKETING = 'Marketing',
  ALL_JOB = 'all-job',
}

export const listEmploymentType = [
  { id: 'employment-type-1', name: 'Full time', value: EnrollmentStatus['FULL_TIME'] },
  { id: 'employment-type-2', name: 'Part time', value: EnrollmentStatus['PART_TIME'] },
  { id: 'employment-type-3', name: 'All', value: EnrollmentStatus['ALL_TYPE'] },
];

export const listExperienceLevel = [
  { id: 'employment-level-1', name: 'Intern', value: ExperienceLevel['INTERN'] },
  { id: 'employment-level-2', name: 'Junior', value: ExperienceLevel['JUNIOR'] },
  { id: 'employment-level-3', name: 'Middle', value: ExperienceLevel['MIDDLE'] },
  { id: 'employment-level-4', name: 'Senior', value: ExperienceLevel['SENIOR'] },
  { id: 'employment-level-5', name: 'All levels', value: ExperienceLevel['ALL_LEVEL'] },
];

export const listJobTag = [
  { id: 'job-tag-1', name: 'Frontend', value: [JobTag['FRONTEND']] },
  { id: 'job-tag-2', name: 'Backend', value: [JobTag['BACKEND']] },
  { id: 'job-tag-3', name: 'Analytics', value: [JobTag['ANALYTICS']] },
  { id: 'job-tag-4', name: 'Design', value: [JobTag['DESIGN']] },
  {
    id: 'job-tag-5',
    name: 'Engineering',
    value: [
      JobTag['ENGINEERING'],
      JobTag['SITE_RELIABILITY'],
      JobTag['DATA_ENGINEER'],
      JobTag['SECURITY_ENGINEER'],
    ],
  },
  { id: 'job-tag-6', name: 'iOS', value: [JobTag['IOS']] },
  { id: 'job-tag-7', name: 'Android', value: [JobTag['ANDROID']] },
  { id: 'job-tag-8', name: 'Tester', value: [JobTag['TESTER']] },
  {
    id: 'job-tag-9',
    name: 'Management',
    value: [JobTag['MANAGEMENT'], JobTag['MARKETING_MANAGER']],
  },
  { id: 'job-tag-10', name: 'AI', value: [JobTag['AI_ENGINEER']] },
  { id: 'job-tag-11', name: 'Marketing', value: [JobTag['MARKETING']] },
  {
    id: 'job-tag-12',
    name: 'Business',
    value: [JobTag['BIZ_DEVELOPMENT_EXECUTIVE'], JobTag['BUSINESS']],
  },
  { id: 'job-tag-13', name: 'All team', value: JobTag['ALL_JOB'] },
];

export interface Job {
  id: string;
  position: string;
  tag: JobTag;
  location: Location[];
  requirements?: string[];
  aboutJob?: string;
  responsibilities?: string[];
  qualifications?: string[];
  technologies?: string[];
  niceToHave?: string[];
  benefits?: string[];
  skills?: string[];
  experienceLevel: ExperienceLevel;
  enrollmentStatus: EnrollmentStatus[];
  createdAt: string;
  slug: string;
  offers?: string[];
  forwardToUrl?: string;
}

export const vacancies: Job[] = [
  {
    id: 'job-1',
    position: 'Software Engineer Intern (Ngu Hanh Son District, Da Nang City)',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      '3rd/4th-year undergrad student or grad student in Information Technology major.',
      'Experience in Software Development and coding in a general-purpose programming language.',
      'Experience with data structures or algorithms gathered from inside or outside of school or work.',
      'Strong problem-solving and analytical skills, with keen attention to detail.',
      'Proficient use of the English language in spoken and written form.',
    ],
    responsibilities: [
      'Analyze requirements, design, programming, and perform testing based on the established design.',
      'Resolve technical issues through debugging, research, and investigation.',
      'Participate in cross-functional build/configuration activities to ensure effective and efficient new or enhanced software engineering designs.',
      'Communicate, collaborate, and work effectively as part of a distributed team across various features.',
    ],
    aboutJob:
      'We are looking for young talents with fresh ideas and an enthusiastic approach to building software. We are expecting to find someone with a strong will to learn the latest concepts in web development and contribute to our team as well as learn from professional software engineers as mentors. This position is an entry point for a full-time or part-time position within one of our project teams as a software engineer.\n\nDuring the Spartan internship program, which can range from one to six months, you will get the chance to work closely with our skilled tech engineers, engaging in hands-on experience.',
    tag: JobTag['ENGINEERING'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Data structures', 'Algorithms', 'Problem-solving', 'English'],
    experienceLevel: ExperienceLevel['INTERN'],
    enrollmentStatus: [EnrollmentStatus['PART_TIME'], EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/software-engineer-intern-danang',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/38',
  },
  {
    id: 'job-20',
    position: 'Software Engineer Intern (District 3, Ho Chi Minh City)',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      '3rd/4th-year undergrad student or grad student in Information Technology major.',
      'Experience in Software Development and coding in a general-purpose programming language.',
      'Experience with data structures or algorithms gathered from inside or outside of school or work.',
      'Strong problem-solving and analytical skills, with keen attention to detail.',
      'Proficient use of the English language in spoken and written form.',
    ],
    responsibilities: [
      'Analyze requirements, design, programming, and perform testing based on the established design.',
      'Resolve technical issues through debugging, research, and investigation.',
      'Participate in cross-functional build/configuration activities to ensure effective and efficient new or enhanced software engineering designs.',
      'Communicate, collaborate, and work effectively as part of a distributed team across various features.',
    ],
    aboutJob:
      'We are looking for young talents with fresh ideas and an enthusiastic approach to building software. We are expecting to find someone with a strong will to learn the latest concepts in web development and contribute to our team as well as learn from professional software engineers as mentors. This position is an entry point for a full-time or part-time position within one of our project teams as a software engineer.\n\nDuring the Spartan internship program, which can range from one to six months, you will get the chance to work closely with our skilled tech engineers, engaging in hands-on experience.',
    tag: JobTag['ENGINEERING'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Data structures', 'Algorithms', 'Problem-solving', 'English'],
    experienceLevel: ExperienceLevel['INTERN'],
    enrollmentStatus: [EnrollmentStatus['PART_TIME'], EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/software-engineer-intern-hochiminh',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/69',
  },
  {
    id: 'job-2',
    position: 'Senior Android Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with native Android development.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Experience developing native Android applications in Java/Kotlin.',
      'Deep understanding of the value of dependency injection and testing.',
      'Experience with one of the following Android architecture patterns: MVP, MVVM, MVI.',
    ],
    technologies: [
      'Java/Kotlin.',
      'RxJava/RxKotlin or Kotlin Coroutines for reactive paradigm.',
      'Dagger for DI.',
    ],
    responsibilities: [
      'Be part of the engineering team where we architecture and implement new features.',
      'Build Android applications for various startups.',
      'Strong focus on high-quality mobile UI.',
      'Work closely with various business partners (backend, UI/UX).',
      'Writing functional and integration tests.',
    ],
    aboutJob:
      'We are looking for an experienced Senior Android Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['ANDROID'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Java/Kotlin', 'RxJava/RxKotlin', 'Dagger'],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/senior-android-engineer',
  },
  {
    id: 'job-3',
    position: 'Senior iOS Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with native iOS development.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Experience developing native iOS applications in Swift.',
      'Deep understanding of the value of dependency injection and testing.',
      'Experience with one of the following iOS architecture patterns: MVP, MVVM, MVI.',
    ],
    technologies: ['Swift', 'RxSwift for reactive paradigm.', 'Swiinject for DI.'],
    responsibilities: [
      'Be part of the engineering team where we architecture and implement new features.',
      'Build iOS applications for various startups.',
      'Strong focus on high-quality mobile UI.',
      'Work closely with various business partners (backend, UI/UX).',
      'Writing functional and integration tests.',
    ],
    aboutJob:
      'We are looking for an experienced Senior iOS Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['IOS'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Swift', 'RxSwift', 'Swinject'],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/senior-ios-engineer',
  },
  {
    id: 'job-15',
    position: 'Senior AI/LLM Engineer (Ngu Hanh Son District, Da Nang City)',
    aboutJob:
      'Our team is growing because our customer is growing, which means we need you! We are looking for an experienced Senior AI Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    responsibilities: [
      'Develop and implement NLP algorithms and models, such as sentiment analysis, text classification, and chatbots.',
      'Prepare text data for model training by cleaning, normalizing, labeling, and vectorizing.',
      'Train, evaluate, and optimize NLP models, such as BERT, GPT-3, and RNNs.',
      'Deploy NLP models to production while monitoring their performance.',
      'Research advances in NLP and integrate them into existing pipelines.',
      'Collaborate with linguists, engineers, and product teams to identify NLP opportunities.',
      'Maintain documentation on NLP architectures, code, and model metrics.',
      'Possess good communication skills in English, including fluency and confidence in communication.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers',
      "Bachelor's degree in Computer Science or related field",
      '1 - 5+ years of experience with either one of the following programming languages: Python/Java/Kotlin/Scala/Go/Rust/C#',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms',
      'Deep understanding of the value of dependency injection and testing',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing',
    ],
    benefits: [
      '100% salary during probation',
      'Competitive compensation packages',
      'Diamond package Health care from Bao Viet Insurance',
      'Technical, Soft skills, English Training courses',
      'An open and transparent culture where people are valued, treated fairly, trusted, and empowered',
      'Training and career development opportunities',
      'Flexible Working Time and Hybrid Working - Working from anywhere!',
      'Device Provided',
      'Happy Hour, Company Trip, Year End Party, and many other events',
      'Unlimited paid time off (PTO) - You are entitled to Unlimited Paid Time Off as long as you deliver!',
      'Sponsoring sports participation costs - We have play hours where our team meets up for PS5 Gaming and Football sessions.',
      'Challenging yourself with high and difficult goals by participating in unprecedented business models in the market.',
      'Working in an Agile environment that is highly flexible and open, eager to incubate any valuable idea.',
    ],
    tag: JobTag['AI_ENGINEER'],
    skills: ['Python', 'Java', 'Kotlin', 'Scala', 'Go', 'Rust', 'C#'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/17/2024',
    slug: '/apply-job/senior-ai-engineer-danang',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/58',
  },
  {
    id: 'job-16',
    position: 'Senior AI/LLM Engineer (District 3, Ho Chi Minh City)',
    aboutJob:
      'Our team is growing because our customer is growing, which means we need you! We are looking for an experienced Senior AI Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    responsibilities: [
      'Develop and implement NLP algorithms and models, such as sentiment analysis, text classification, and chatbots.',
      'Prepare text data for model training by cleaning, normalizing, labeling, and vectorizing.',
      'Train, evaluate, and optimize NLP models, such as BERT, GPT-3, and RNNs.',
      'Deploy NLP models to production while monitoring their performance.',
      'Research advances in NLP and integrate them into existing pipelines.',
      'Collaborate with linguists, engineers, and product teams to identify NLP opportunities.',
      'Maintain documentation on NLP architectures, code, and model metrics.',
      'Possess good communication skills in English, including fluency and confidence in communication.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers',
      "Bachelor's degree in Computer Science or related field",
      '1 - 5+ years of experience with either one of the following programming languages: Python/Java/Kotlin/Scala/Go/Rust/C#',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms',
      'Deep understanding of the value of dependency injection and testing',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing',
    ],
    benefits: [
      '100% salary during probation',
      'Competitive compensation packages',
      'Diamond package Health care from Bao Viet Insurance',
      'Technical, Soft skills, English Training courses',
      'An open and transparent culture where people are valued, treated fairly, trusted, and empowered',
      'Training and career development opportunities',
      'Flexible Working Time and Hybrid Working - Working from anywhere!',
      'Device Provided',
      'Happy Hour, Company Trip, Year End Party, and many other events',
      'Unlimited paid time off (PTO) - You are entitled to Unlimited Paid Time Off as long as you deliver!',
      'Sponsoring sports participation costs - We have play hours where our team meets up for PS5 Gaming and Football sessions.',
      'Challenging yourself with high and difficult goals by participating in unprecedented business models in the market.',
      'Working in an Agile environment that is highly flexible and open, eager to incubate any valuable idea.',
    ],
    tag: JobTag['AI_ENGINEER'],
    skills: ['Python', 'Java', 'Kotlin', 'Scala', 'Go', 'Rust', 'C#'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/17/2024',
    slug: '/apply-job/senior-ai-engineer-hochiminh',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/63',
  },
  {
    id: 'job-17',
    position: 'Senior Fullstack Engineer (Ngu Hanh Son District, Da Nang City)',
    requirements: [
      'Fluent in English, able to communicate directly with customers',
      `Bachelor's degree in Computer Science, Computer Engineering, Information Systems, or a related field.`,
      '2-5+ years of practical experience developing modern web applications within a software development team and successfully deploying products into production.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Deep understanding of the value of dependency injection and testing.',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing.',
      'Positive and solution-oriented mindset.',
      'Self-motivated & self-managing, with strong organizational skills.',
      'Effective communication skills: Regularly achieve consensus with peers and clear status updates.',
      'An inclination towards communication, inclusion, and visibility.',
      'Experience with Kafka, MQTT, etc',
      'Experience with AI/LLM will be a big plus.',
    ],
    responsibilities: [
      'Design, build, deploy & maintain high-performance web applications and APIs to ensure seamless operation.',
      'Design client-side and server-side architecture',
      'Collaborating with the client during the design and implementation phase',
      'Write high-quality code, including comprehensive unit, functional, and end-to-end tests.',
      'Participate in technical prototyping, technical design & code review.',
      'Collaborate with team members to communicate and negotiate technical solutions and architectural designs.',
      'Lead technical initiatives and integrate efforts across teams and products.',
    ],
    aboutJob:
      'We are seeking an experienced Senior Full Stack Software Engineer to join our Spartan Team. We desire someone passionate about building and testing software, and who enjoys collaborating closely with various stakeholders to deliver exceptional software solutions. In this role, you will tackle challenging problems, engage with the latest technology stack, and collaborate with skilled engineers to make significant impacts.',
    tag: JobTag['ENGINEERING'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: [
      'DevOps',
      'SRE',
      'AI/LLM',
      'Java',
      'Kotlin',
      'Python',
      'Go',
      'Rust',
      'Ruby',
      'Typescript',
    ],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2024',
    slug: '/apply-job/senior-fullstack-engineer-danang',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/62',
  },
  {
    id: 'job-18',
    position: 'Senior Fullstack Engineer (District 3, Ho Chi Minh City)',
    requirements: [
      'Fluent in English, able to communicate directly with customers',
      `Bachelor's degree in Computer Science, Computer Engineering, Information Systems, or a related field.`,
      '2-5+ years of practical experience developing modern web applications within a software development team and successfully deploying products into production.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Deep understanding of the value of dependency injection and testing.',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing.',
      'Positive and solution-oriented mindset.',
      'Self-motivated & self-managing, with strong organizational skills.',
      'Effective communication skills: Regularly achieve consensus with peers and clear status updates.',
      'An inclination towards communication, inclusion, and visibility.',
      'Experience with Kafka, MQTT, etc',
      'Experience with AI/LLM will be a big plus.',
    ],
    responsibilities: [
      'Design, build, deploy & maintain high-performance web applications and APIs to ensure seamless operation.',
      'Design client-side and server-side architecture',
      'Collaborating with the client during the design and implementation phase',
      'Write high-quality code, including comprehensive unit, functional, and end-to-end tests.',
      'Participate in technical prototyping, technical design & code review.',
      'Collaborate with team members to communicate and negotiate technical solutions and architectural designs.',
      'Lead technical initiatives and integrate efforts across teams and products.',
    ],
    aboutJob:
      'We are seeking an experienced Senior Full Stack Software Engineer to join our Spartan Team. We desire someone passionate about building and testing software, and who enjoys collaborating closely with various stakeholders to deliver exceptional software solutions. In this role, you will tackle challenging problems, engage with the latest technology stack, and collaborate with skilled engineers to make significant impacts.',
    tag: JobTag['ENGINEERING'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: [
      'DevOps',
      'SRE',
      'AI/LLM',
      'Java',
      'Kotlin',
      'Python',
      'Go',
      'Rust',
      'Ruby',
      'Typescript',
    ],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2024',
    slug: '/apply-job/senior-fullstack-engineer-hochiminh',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/61',
  },
  {
    id: 'job-19',
    position: 'Security Engineer (Ngu Hanh Son District, Da Nang City)',
    aboutJob:
      'We are looking for an experienced Security Engineer to join our Spartan Team. Construction enthusiast who works closely with a variety of stakeholders to identify, assess, and resolve security vulnerabilities, implement security measures, and monitor and detect unusual activities. Often online, and take precautions to ensure the security of Spartan systems. You will be able to solve challenging problems, work with the latest technology teams, and work with talented engineers to contribute in a meaningful way.',
    responsibilities: [
      'Develop, execute and track the performance of security measures to protect information and network infrastructure and computer systems.',
      'Design computer security strategy and engineer comprehensive cybersecurity architecture.',
      'Identify, define and document system security requirements and recommend solutions to management.',
      'Configure, troubleshoot and maintain security infrastructure software and hardware.',
      'Install software that monitors systems and networks for security breaches and intrusions.',
      'Monitor systems for irregular behavior and set up preventive measures.',
      'Plan, develop, implement and update company’s information security strategy.',
      'Educate and train staff on information system security best practices.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      'Bachelor of Science in Computer Science or a related field.',
      'Three or more years’ work experience as a System Security Engineer or related position.',
      'Proven experience developing, operating and maintaining security systems.',
      'Extensive knowledge of operating system and database security.',
      'Proficiency in networking technologies, network security and network monitoring solutions.',
      'Knowledge of security systems including anti-virus applications, content filtering, firewalls, authentication systems and intrusion detection and notification systems.',
      'In-depth knowledge of security protocols and principles.',
      'Critical thinking skills and ability to solve complex problems.',
    ],
    benefits: [
      '100% salary during probation',
      'Competitive compensation packages',
      'Diamond package Health care from Bao Viet Insurance',
      'Technical, Soft skills, English Training courses',
      'An open and transparent culture where people are valued, treated fairly, trusted, and empowered',
      'Training and career development opportunities',
      'Flexible Working Time and Hybrid Working - Working from anywhere!',
      'Device Provided',
      'Happy Hour, Company Trip, Year End Party, and many other events',
      'Unlimited paid time off (PTO) - You are entitled to Unlimited Paid Time Off as long as you deliver!',
      'Sponsoring sports participation costs - We have play hours where our team meets up for PS5 Gaming and Football sessions.',
      'Challenging yourself with high and difficult goals by participating in unprecedented business models in the market.',
      'Working in an Agile environment that is highly flexible and open, eager to incubate any valuable idea.',
    ],
    tag: JobTag['SECURITY_ENGINEER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Network Security', 'System Security', 'Cybersecurity'],
    experienceLevel: ExperienceLevel['MIDDLE'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2024',
    slug: '/apply-job/security-engineer-danang',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/66',
  },
  {
    id: 'job-20',
    position: 'Security Engineer (District 3, Ho Chi Minh City)',
    aboutJob:
      'We are looking for an experienced Security Engineer to join our Spartan Team. Construction enthusiast who works closely with a variety of stakeholders to identify, assess, and resolve security vulnerabilities, implement security measures, and monitor and detect unusual activities. Often online, and take precautions to ensure the security of Spartan systems. You will be able to solve challenging problems, work with the latest technology teams, and work with talented engineers to contribute in a meaningful way.',
    responsibilities: [
      'Develop, execute and track the performance of security measures to protect information and network infrastructure and computer systems.',
      'Design computer security strategy and engineer comprehensive cybersecurity architecture.',
      'Identify, define and document system security requirements and recommend solutions to management.',
      'Configure, troubleshoot and maintain security infrastructure software and hardware.',
      'Install software that monitors systems and networks for security breaches and intrusions.',
      'Monitor systems for irregular behavior and set up preventive measures.',
      'Plan, develop, implement and update company’s information security strategy.',
      'Educate and train staff on information system security best practices.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      'Bachelor of Science in Computer Science or a related field.',
      'Three or more years’ work experience as a System Security Engineer or related position.',
      'Proven experience developing, operating and maintaining security systems.',
      'Extensive knowledge of operating system and database security.',
      'Proficiency in networking technologies, network security and network monitoring solutions.',
      'Knowledge of security systems including anti-virus applications, content filtering, firewalls, authentication systems and intrusion detection and notification systems.',
      'In-depth knowledge of security protocols and principles.',
      'Critical thinking skills and ability to solve complex problems.',
    ],
    benefits: [
      '100% salary during probation',
      'Competitive compensation packages',
      'Diamond package Health care from Bao Viet Insurance',
      'Technical, Soft skills, English Training courses',
      'An open and transparent culture where people are valued, treated fairly, trusted, and empowered',
      'Training and career development opportunities',
      'Flexible Working Time and Hybrid Working - Working from anywhere!',
      'Device Provided',
      'Happy Hour, Company Trip, Year End Party, and many other events',
      'Unlimited paid time off (PTO) - You are entitled to Unlimited Paid Time Off as long as you deliver!',
      'Sponsoring sports participation costs - We have play hours where our team meets up for PS5 Gaming and Football sessions.',
      'Challenging yourself with high and difficult goals by participating in unprecedented business models in the market.',
      'Working in an Agile environment that is highly flexible and open, eager to incubate any valuable idea.',
    ],
    tag: JobTag['SECURITY_ENGINEER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Network Security', 'System Security', 'Cybersecurity'],
    experienceLevel: ExperienceLevel['MIDDLE'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2024',
    slug: '/apply-job/security-engineer-hochiminh',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/65',
  },
  {
    id: 'job-12',
    position: 'Senior Sales Development Manager',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      `Bachelor's degree in Business Administration, Marketing, or a related field.`,
      'Demonstrable track record of sales achievement and excellence in the software consulting or IT industry.',
      'Strong understanding of software solutions, technologies, and consulting services.',
      'Exceptional communication, negotiation, and presentation skills.',
      'Strategic thinker with the ability to analyze data, make data-driven decisions, and adapt to market changes.',
      'Proficiency in CRM software and other sales tools.',
      'Self-motivated, results-oriented, and a team player.',
    ],
    responsibilities: [
      'Collaborate with sales and engineering teams to grasp client needs and offer technical solutions or alternatives as needed.',
      'Lead the sales process from initial assessment to project estimation and closure, closely coordinating with internal teams.',
      'Efficiently manage lead lists, meeting or exceeding SLAs, and regularly update activity and contact details in the CRM system to facilitate accurate weekly reporting.',
      'Create sales presentations and project proposal decks to secure key sales accounts.',
      'Inform clients about our services and engagement models in user experience design, software development, and project management.',
      'Partner with clients to clarify requirements and communicate these to design and engineering teams.',
      'Evaluate project assumptions and estimates provided by internal development and design teams.',
      'Draft master service agreements and statements of work for new clients and projects.',
      'Establish and nurture client relationships, including regular meetings with current and prospective clients.',
    ],
    aboutJob:
      'We are looking for an experienced (Senior) Sales Development Manager to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['BIZ_DEVELOPMENT_EXECUTIVE'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2024',
    slug: '/apply-job/senior-sales-development-manager',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/68',
  },
  {
    id: 'job-13',
    position: 'Digital Marketing Intern (District 3, Ho Chi Minh City)',
    requirements: [
      'Currently pursuing or recently completed a degree in Marketing, Communications, Business, or a related field.',
      'Excellent writing and editing skills with a keen eye for detail.',
      'Basic knowledge of social media platforms and trends.',
      'Creative mindset with a passion for staying updated on the latest digital marketing trends and techniques.',
    ],
    responsibilities: [
      'Conduct keyword research and analysis to identify opportunities and trends.',
      'Create high-quality, engaging, and SEO-optimized content for our website, blog, social media, and other digital platforms.',
      'Assist in the planning, creation, and execution of digital advertising campaigns across various platforms (Google Ads, social media, etc.).',
      'Monitor and analyze the performance of digital ads, providing insights and recommendations for optimization.',
      'Develop content related to IT outsourcing services, showcasing our expertise and solutions.',
      'Use tools such as Google Analytics, Google Search Console, and SEO software (e.g., SEMrush, Ahrefs) to monitor website performance.',
      'Support the management of social media accounts by creating and scheduling posts, and engaging with the audience.',
      'Conduct competitor analysis to stay informed about industry trends and best practices.',
      'Identify opportunities for differentiation and competitive advantage.',
    ],
    aboutJob:
      'We are specializing in IT outsourcing and innovative technology solutions. We are dedicated to providing top-notch services to our clients while fostering a culture of learning and growth within our team. We are currently seeking a proactive and skilled\u2009Digital Marketing Intern\u2009to join our marketing team, focusing on SEO, digital advertising, and content creation, with a keen interest in IT outsourcing and technical writing. We are looking for a proactive Digital Marketing intern to join our marketing team. The perfect candidate will be tasked with creating and executing successful digital marketing strategies aimed at increasing online traffic, engagement, and conversions. This position demands a mix of creativity, analytical thinking, and technical proficiency to oversee diverse digital marketing channels.',
    tag: JobTag['MARKETING'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Marketing', 'Communications', 'Business'],
    experienceLevel: ExperienceLevel['INTERN'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2024',
    slug: '/apply-job/digital-marketing-intern',
    forwardToUrl: 'https://spartandev.bamboohr.com/careers/67',
  },
];
