export enum EnrollmentStatus {
  FULL_TIME = 'full-time',
  PART_TIME = 'part-time',
  ALL_TYPE = 'all-type',
}
export enum Location {
  REMOTE = 'remote',
  OFFICE = 'office',
}
export enum ExperienceLevel {
  INTERN = 'intern',
  JUNIOR = 'junior',
  MIDDLE = 'middle',
  SENIOR = 'senior',
  ALL_LEVEL = 'all-level',
}
export enum JobTag {
  FRONTEND = 'Front-end',
  ENGINEERING = 'Engineering',
  ANDROID = 'Android',
  BACKEND = 'Backend',
  ANALYTICS = 'Analytics',
  DESIGN = 'Design',
  TESTER = 'Tester',
  MANAGEMENT = 'Management',
  IOS = 'iOS',
  SITE_RELIABILITY = 'Site Reliability',
  DATA_ENGINEER = 'Data Engineer',
  AI_ENGINEER = 'AI/LLM Engineer',
  SECURITY_ENGINEER = 'Security Engineer',
  BIZ_DEVELOPMENT_EXECUTIVE = 'Business Development Executive',
  MARKETING_MANAGER = 'Marketing Manager - Software',
  ALL_JOB = 'all-job',
}

export const listEmploymentType = [
  { id: 'employment-type-1', name: 'Full time', value: EnrollmentStatus['FULL_TIME'] },
  { id: 'employment-type-2', name: 'Part time', value: EnrollmentStatus['PART_TIME'] },
  { id: 'employment-type-3', name: 'All', value: EnrollmentStatus['ALL_TYPE'] },
];

export const listExperienceLevel = [
  { id: 'employment-level-1', name: 'Intern', value: ExperienceLevel['INTERN'] },
  { id: 'employment-level-2', name: 'Junior', value: ExperienceLevel['JUNIOR'] },
  { id: 'employment-level-3', name: 'Middle', value: ExperienceLevel['MIDDLE'] },
  { id: 'employment-level-4', name: 'Senior', value: ExperienceLevel['SENIOR'] },
  { id: 'employment-level-5', name: 'All levels', value: ExperienceLevel['ALL_LEVEL'] },
];

export const listJobTag = [
  { id: 'job-tag-1', name: 'Frontend', value: [JobTag['FRONTEND']] },
  { id: 'job-tag-2', name: 'Backend', value: [JobTag['BACKEND']] },
  { id: 'job-tag-3', name: 'Analytics', value: [JobTag['ANALYTICS']] },
  { id: 'job-tag-4', name: 'Design', value: [JobTag['DESIGN']] },
  {
    id: 'job-tag-5',
    name: 'Engineering',
    value: [
      JobTag['ENGINEERING'],
      JobTag['SITE_RELIABILITY'],
      JobTag['DATA_ENGINEER'],
      JobTag['SECURITY_ENGINEER'],
    ],
  },
  { id: 'job-tag-6', name: 'iOS', value: [JobTag['IOS']] },
  { id: 'job-tag-7', name: 'Android', value: [JobTag['ANDROID']] },
  { id: 'job-tag-8', name: 'Tester', value: [JobTag['TESTER']] },
  {
    id: 'job-tag-9',
    name: 'Management',
    value: [JobTag['MANAGEMENT'], JobTag['MARKETING_MANAGER']],
  },
  { id: 'job-tag-10', name: 'AI', value: [JobTag['AI_ENGINEER']] },
  { id: 'job-tag-11', name: 'Business', value: [JobTag['BIZ_DEVELOPMENT_EXECUTIVE']] },
  { id: 'job-tag-12', name: 'All team', value: JobTag['ALL_JOB'] },
];

export interface Job {
  id: string;
  position: string;
  tag: JobTag;
  location: Location[];
  requirements?: string[];
  aboutJob?: string;
  responsibilities?: string[];
  qualifications?: string[];
  technologies?: string[];
  skills?: string[];
  experienceLevel: ExperienceLevel;
  enrollmentStatus: EnrollmentStatus[];
  createdAt: string;
  slug: string;
  offers?: string[];
}

export const vacancies: Job[] = [
  {
    id: 'job-1',
    position: 'Software Engineer Intern',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      '3rd/4th-year undergrad student or grad student in Information Technology major.',
      'Experience in Software Development and coding in a general-purpose programming language.',
      'Experience with data structures or algorithms gathered from inside or outside of school or work.',
      'Strong problem-solving and analytical skills, with keen attention to detail.',
      'Proficient use of the English language in spoken and written form.',
    ],
    responsibilities: [
      'Analyze requirements, design, programming, and perform testing based on the established design.',
      'Resolve technical issues through debugging, research, and investigation.',
      'Participate in cross-functional build/configuration activities to ensure effective and efficient new or enhanced software engineering designs.',
      'Communicate, collaborate, and work effectively as part of a distributed team across various features.',
    ],
    aboutJob:
      'We are looking for young talents with fresh ideas and an enthusiastic approach to building software. We are expecting to find someone with a strong will to learn the latest concepts in web development and contribute to our team as well as learn from professional software engineers as mentors. This position is an entry point for a full-time or part-time position within one of our project teams as a software engineer.\n\nDuring the Spartan internship program, which can range from one to six months, you will get the chance to work closely with our skilled tech engineers, engaging in hands-on experience.',
    tag: JobTag['ENGINEERING'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Data structures', 'Algorithms', 'Problem-solving', 'English'],
    experienceLevel: ExperienceLevel['INTERN'],
    enrollmentStatus: [EnrollmentStatus['PART_TIME'], EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/software-engineer-intern',
  },
  {
    id: 'job-2',
    position: 'Senior Android Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with native Android development.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Experience developing native Android applications in Java/Kotlin.',
      'Deep understanding of the value of dependency injection and testing.',
      'Experience with one of the following Android architecture patterns: MVP, MVVM, MVI.',
    ],
    technologies: [
      'Java/Kotlin.',
      'RxJava/RxKotlin or Kotlin Coroutines for reactive paradigm.',
      'Dagger for DI.',
    ],
    responsibilities: [
      'Be part of the engineering team where we architecture and implement new features.',
      'Build Android applications for various startups.',
      'Strong focus on high-quality mobile UI.',
      'Work closely with various business partners (backend, UI/UX).',
      'Writing functional and integration tests.',
    ],
    aboutJob:
      'We are looking for an experienced Senior Android Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['ANDROID'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Java/Kotlin', 'RxJava/RxKotlin', 'Dagger'],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/senior-software-engineer-android',
  },
  {
    id: 'job-3',
    position: 'Senior iOS Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with native iOS development.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Experience developing native iOS applications in Swift.',
      'Deep understanding of the value of dependency injection and testing.',
      'Experience with one of the following iOS architecture patterns: MVP, MVVM, MVI.',
    ],
    technologies: ['Swift', 'RxSwift for reactive paradigm.', 'Swiinject for DI.'],
    responsibilities: [
      'Be part of the engineering team where we architecture and implement new features.',
      'Build iOS applications for various startups.',
      'Strong focus on high-quality mobile UI.',
      'Work closely with various business partners (backend, UI/UX).',
      'Writing functional and integration tests.',
    ],
    aboutJob:
      'We are looking for an experienced Senior iOS Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['IOS'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: ['Swift', 'RxSwift', 'Swiinject'],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/senior-software-engineer-ios',
  },
  {
    id: 'job-4',
    position: 'Senior Backend Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with Java/Kotlin/.NET.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Deep understanding of the value of dependency injection and testing.',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing.',
    ],
    technologies: [
      'Java/Kotlin/.NET/Terraform/Typescript.',
      'Jenkins.',
      'Postgresql, Redis, Kafka.',
      'AWS/GCP.',
    ],
    responsibilities: [
      'Work with a cross-functional team to deliver timely, high-quality, and well-tested code.',
      'Observe and enforce standards regarding code quality and test coverage.',
      'Help continue to build the engineering culture at Spartan.',
      'Design and build large-scale microservices for various startups.',
    ],
    aboutJob:
      "We are seeking an experienced Senior Backend Engineer to join our Spartan Team. We desire someone who is passionate about building and testing software, and who enjoys collaborating closely with various stakeholders to deliver exceptional software solutions. In this role, you'll tackle challenging problems, engage with the latest technology stack, and collaborate with skilled engineers to make a significant contribution.",
    tag: JobTag['BACKEND'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: [
      'Java',
      'Kotlin',
      '.NET',
      'Terraform',
      'Typescript',
      'Jenkins',
      'Postgresql',
      'Redis',
      'Kafka',
      'AWS',
      'GCP',
    ],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/senior-software-engineer-backend',
  },
  {
    id: 'job-5',
    position: 'Senior Frontend Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience as a Frontend Developer, with a focus on web application development.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Strong proficiency in frontend technologies such as HTML5, CSS3, JavaScript, and modern JavaScript frameworks (e.g., React, Angular, Vue.js).',
      'Experience with frontend build tools, package managers, and version control systems (e.g., Webpack, npm, Git).',
      'Strong problem-solving and analytical skills, with keen attention to detail.',
    ],
    technologies: [
      'ReactJs/nextJs',
      'JavaScript (ES6+), TypeScript',
      'UI Component Libraries: Material-UI, Ant Design, Bootstrap',
      'State Management: Redux, Rematch',
      'Routing: React Router',
      'Testing: Jest, Enzyme, React Testing Library',
      'Build Tools: Webpack, Babel',
      'Version Control: Git, GitHub, GitLab',
      'Package Managers: npm, Yarn',
      'Code Quality and Linting: ESLint, Prettier',
      'DevOps and Deployment: Docker, AWS',
      'Continuous Integration and Deployment: Jenkins, AWS Amplify',
      'Collaboration and Communication: Slack, Jira, Confluence',
    ],
    responsibilities: [
      'Collaborate with designers and backend developers to translate wireframes and UI/UX designs into functional and interactive web interfaces.',
      'Write clean, efficient, and maintainable code using HTML, CSS, and JavaScript to implement responsive and cross-browser-compatible interfaces.',
      'Ensure that the web applications are optimized for maximum speed and scalability.',
      'Conduct thorough testing and debugging of frontend components to ensure high-quality and bug-free code.',
      'Collaborate with the development team to continuously improve the user experience and implement new features and enhancements.',
      'Stay up-to-date with the latest front-end development trends and best practices and apply them to improve the quality and performance of our web applications.',
      'Participate in code reviews and provide constructive feedback to ensure adherence to coding standards and best practices.',
    ],
    aboutJob:
      'We are looking for an experienced Senior Frontend Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['FRONTEND'],
    location: [Location['REMOTE'], Location['OFFICE']],
    skills: [
      'Frontend Development',
      'HTML5',
      'CSS3',
      'JavaScript',
      'React.js',
      'Webpack',
      'Git',
      'Redux',
      'TypeScript',
      'Testing',
    ],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/senior-software-engineer-frontend',
  },
  {
    id: 'job-6',
    position: 'Senior Site Reliability Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science, Information Technology, or a related field (or equivalent work experience).",
      '3+ years of experience as an SRE Engineer or DevOps Engineer or similar role.',
      'Strong knowledge of cloud platforms such as AWS, Azure, or Google Cloud, including infrastructure services and best practices.',
      'Familiarity with containerization technologies and orchestration frameworks (e.g., Docker, Kubernetes).',
      'Solid understanding of version control systems (e.g., Git) and their integration with CI/CD pipelines.',
      'Experience with IAC tools like Terraform, CloudFormation, or similar.',
      'Strong problem-solving skills and the ability to troubleshoot complex issues across the entire technology stack.',
      'Excellent communication and collaboration skills to work effectively with cross-functional teams.',
    ],
    technologies: [
      'AWS/GCP/Azure',
      'Docker/Kubernetes/ECS',
      'Jenkins/Github Action',
      'Terraform/CloudFormation',
      'Python/Kotlin',
      'Datadog',
    ],
    responsibilities: [
      'Design, implement, and manage the CI/CD pipelines for the continuous integration, delivery, and deployment of applications and services.',
      'Collaborate with development teams to integrate automated testing and quality assurance into the CI/CD pipelines.',
      'Work with operations teams to ensure the reliability, scalability, and performance of production systems.',
      'Monitor and analyze system performance metrics, implementing improvements and optimizations when necessary.',
      'Implement and manage infrastructure as code (IAC) using tools such as Terraform, CloudFormation, or similar, to automate the provisioning and configuration of cloud resources.',
      'Implement and maintain containerization technologies (e.g., Docker, Kubernetes) to facilitate application deployment and scaling.',
      'Automate repetitive tasks and processes to increase operational efficiency, using scripting languages like Python, Shell Script, …',
      'Ensure security best practices are implemented throughout the infrastructure and application layers.',
      'Participate in incident response and root cause analysis, implementing preventive measures to avoid future incidents.',
      'Provide technical leadership, mentorship, and guidance to junior members of the SRE team.',
      'Stay up-to-date with industry trends, emerging technologies, and best practices to continuously improve the DevOps processes and infrastructure.',
    ],
    aboutJob:
      'We are looking for an experienced Senior Site Reliability Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['SITE_RELIABILITY'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '08/17/2023',
    slug: '/apply-job/senior-site-reliability-engineer',
  },
  {
    id: 'job-7',
    position: 'Senior Data Engineer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with either one of the following programming languages Java/Kotlin/Scala/Go/Rust/C#/Python.',
      'Excellent understanding of SQL.',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing.',
    ],
    responsibilities: [
      'Select and maintain appropriate data storage solutions, including databases (SQL and NoSQL), data lakes, and cloud storage services.',
      'Optimize data storage for efficient querying and retrieval.',
      'Build and maintain ETL processes to move and transform data between different systems and storage platforms.',
      'Tune and optimize data pipelines and database queries for performance and scalability.',
      'Create and maintain data models, schemas, and data dictionaries to support analytics and reporting needs.',
      'Implement dimension modeling for data warehousing.',
      'Manage and maintain the infrastructure, including servers, clusters, and cloud resources, to support data processing and storage needs.',
      'Explore and understand data to identify patterns, trends, and anomalies.',
      'Conduct initial data analysis to gain insights.',
      'Write complex and performant SQL queries to develop the required algorithms.',
      'Create visualizations (charts, graphs, dashboards) to present data insights effectively.',
      'Use tools like Redash, Metabase for data modeling and visualization.',
      'Use tools like Tableau, Google Looker, or Python libraries (Matplotlib, Seaborn) for visualization.',
      'Generate regular and ad-hoc reports to communicate insights and findings to stakeholders.',
      'Collaborate with business teams to define reporting requirements.',
      'Ensure data quality and integrity.',
    ],
    aboutJob:
      "We are seeking an experienced Senior Data Engineer to join our Spartan Team. We desire someone who is passionate about building and testing software, and who enjoys collaborating closely with various stakeholders to deliver exceptional software solutions. In this role, you'll tackle challenging problems, engage with the latest technology stack, and collaborate with skilled engineers to make a significant contribution.",
    tag: JobTag['DATA_ENGINEER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    technologies: [
      'Java, Kotlin, Scala, Go, Rust, C#, Python.',
      'Jenkins, Github Action.',
      'PostgreSQL, MongoDB, DynamoDB, Redis.',
      'SQS, Kafka, GCP Cloud Task.',
      'Spark, Flink.',
      'AWS, GCP, Azure.',
    ],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '07/21/2023',
    slug: '/apply-job/graphic-designer',
  },
  {
    id: 'job-8',
    position: 'Tester (QA/QC)',
    responsibilities: [
      'Collaborate with the QC team to perform testing based on customer requirements.',
      'Analyze and review product requirements to ensure test coverage.',
      'Design and create comprehensive test plans and test cases aligned with business requirements.',
      'Execute test cases to verify the quality and functionality of systems.',
      'Conduct various types of testing, including API testing and functional testing.',
      'Identify issues and recurring patterns to improve system quality.',
      'Make recommendations for enhancing applications based on testing results.',
      'Generate well-structured test plans and associated test cases.',
      'Report and manage defects effectively.',
    ],
    qualifications: [
      'At least 3 year of experience in software testing.',
      'Good communication skills in English, fluency and confidence in communication.',
      'Experience in software testing with a strong quality assurance (QA) mindset.',
      'Proficiency in testing software across different browsers and devices.',
      'Familiarity with Agile methodologies and the ability to work in an Agile team.',
      'Strong analytical skills and a deep understanding of the testing process.',
      'Basic knowledge of MySQL relational databases.',
      'Experience with testing platforms and tools, such as Jira and Postman.',
      'Strong English communication skills, both written and verbal.',
      'Proactive and forward-thinking in your approach to work.',
      'Experience in business analysis and scrum master role is a plus.',
    ],
    aboutJob:
      'We are looking for an experienced Tester (QA/QC) to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['TESTER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['ALL_LEVEL'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '09/29/2023',
    slug: '/apply-job/tester-qa-qc',
  },
  {
    id: 'job-9',
    position: 'UX/UI Designer',
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      'Bachelor’s or Master’s degree in Design, Human-Computer Interaction (HCI), or a related field.',
      'At least 3 years of experience in UX/UI design.',
      'Proficient in design tools such as Figma, Adobe Creative Suite, and InVision.',
      'Strong understanding of user-centered design principles and best practices.',
      'Strong communication and collaboration skills.',
      'Excellent problem-solving, critical thinking, and attention to detail.',
    ],
    responsibilities: [
      'Conduct user research and evaluate user feedback to continuously iterate and improve designs.',
      'Create wireframes, storyboards, user flows, process flows, and site maps to effectively communicate interaction and design ideas.',
      'Collaborate with product managers, engineers, and stakeholders to define and implement innovative solutions for the product direction, visuals, and user experience',
      'Conduct usability testing and analyze results to improve design decisions.',
      'Execute all visual design stages from concept to final hand-off to engineering.',
      'Stay up-to-date with emerging design trends and technologies.',
    ],
    aboutJob:
      'We are seeking a highly skilled creative Product design to join our growing team, Hybrid team. As a Product designer at Spartan Dev you will work directly with our design team and founder. Your work will embody our values of simplicity, support, excellence, and curiosity, ensuring our users have a seamless and intuitive experience while using our platform and customer application, also ideal candidate will have a strong passion for user-centered design and a deep understanding of user experience principles.',
    tag: JobTag['DESIGN'],
    location: [Location['REMOTE'], Location['OFFICE']],
    // skills: [
    //   'Product Design',
    //   'User Experience',
    //   'UI Design',
    //   'Figma',
    //   'Adobe Creative Suite',
    //   'InVision',
    // ],
    experienceLevel: ExperienceLevel['ALL_LEVEL'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '09/29/2023',
    slug: '/apply-job/ui-ux-designer',
  },
  {
    id: 'job-10',
    position: 'AI/LLM Engineer',
    responsibilities: [
      'Develop and implement NLP algorithms and models, such as sentiment analysis, text classification, and chatbots.',
      'Prepare text data for model training by cleaning, normalizing, labeling, and vectorizing.',
      'Train, evaluate, and optimize NLP models, such as BERT, GPT-3, and RNNs.',
      'Deploy NLP models to production while monitoring their performance.',
      'Research advances in NLP and integrate them into existing pipelines.',
      'Collaborate with linguists, engineers, and product teams to identify NLP opportunities.',
      'Maintain documentation on NLP architectures, code, and model metrics.',
      'Possess good communication skills in English, including fluency and confidence in communication.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '1+ years of experience with either one of the following programming languages Python/Java/Kotlin/Scala/Go/Rust/C#',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Deep understanding of the value of dependency injection and testing.',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing.',
    ],
    aboutJob:
      'We are looking for an experienced AI Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['AI_ENGINEER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['ALL_LEVEL'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '11/10/2023',
    slug: '/apply-job/ai-llm-engineer',
  },
  {
    id: 'job-11',
    position: 'Senior AI/LLM Engineer',
    responsibilities: [
      'Develop and implement NLP algorithms and models, such as sentiment analysis, text classification, and chatbots.',
      'Prepare text data for model training by cleaning, normalizing, labeling, and vectorizing.',
      'Train, evaluate, and optimize NLP models, such as BERT, GPT-3, and RNNs.',
      'Deploy NLP models to production while monitoring their performance.',
      'Research advances in NLP and integrate them into existing pipelines.',
      'Collaborate with linguists, engineers, and product teams to identify NLP opportunities.',
      'Maintain documentation on NLP architectures, code, and model metrics.',
      'Possess good communication skills in English, including fluency and confidence in communication.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Computer Science or related field.",
      '3+ years of experience with either one of the following programming languages Python/Java/Kotlin/Scala/Go/Rust/C#',
      'Excellent understanding of computer science fundamentals, data structures, and algorithms.',
      'Deep understanding of the value of dependency injection and testing.',
      'Solid coding practices, including writing technical specifications, peer code review, and unit & integration testing.',
    ],
    aboutJob:
      'We are looking for an experienced AI Engineer to join our Spartan Team. Who is passionate about building, testing, and working closely with various stakeholders to deliver top-notch software. You will be able to solve challenging problems, work with the latest tech stack, and work with talented engineers to contribute meaningfully.',
    tag: JobTag['AI_ENGINEER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['SENIOR'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '11/10/2023',
    slug: '/apply-job/senior-ai-llm-engineer',
  },
  {
    id: 'job-12',
    position: 'Security Engineer',
    responsibilities: [
      'Develop, execute and track the performance of security measures to protect information and network infrastructure and computer systems.',
      'Design computer security strategy and engineer comprehensive cybersecurity architecture.',
      'Identify, define and document system security requirements and recommend solutions to management.',
      'Configure, troubleshoot and maintain security infrastructure software and hardware.',
      'Install software that monitors systems and networks for security breaches and intrusions.',
      'Monitor systems for irregular behavior and set up preventive measures.',
      'Plan, develop, implement and update company’s information security strategy.',
      'Educate and train staff on information system security best practices.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      'Bachelor of Science in Computer Science or a related field.',
      'Three or more years’ work experience as a System Security Engineer or related position.',
      'Proven experience developing, operating and maintaining security systems.',
      'Extensive knowledge of operating system and database security.',
      'Proficiency in networking technologies, network security and network monitoring solutions.',
      'Knowledge of security systems including anti-virus applications, content filtering, firewalls, authentication systems and intrusion detection and notification systems.',
      'In-depth knowledge of security protocols and principles.',
      'Critical thinking skills and ability to solve complex problems.',
    ],
    aboutJob:
      'We are looking for an experienced Security Engineer to join our Spartan Team. Construction enthusiast who works closely with a variety of stakeholders to identify, assess, and resolve security vulnerabilities, implement security measures, and monitor and detect unusual activities. often online, and take precautions to ensure the security of Spartan systems. You will be able to solve challenging problems, work with the latest technology teams, and work with talented engineers to contribute in a meaningful way.',
    tag: JobTag['SECURITY_ENGINEER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['ALL_LEVEL'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '30/10/2023',
    slug: '/apply-job/security-engineer',
  },
  {
    id: 'job-13',
    position: 'Business Development Executive',
    responsibilities: [
      '<b>Market Analysis</b>: Conduct thorough market analysis to identify potential clients, assess industry trends, and evaluate competitors. Maintain a comprehensive understanding of market dynamics to inform strategic decision-making.',
      '<b>Client Acquisition</b>: Identify and target potential clients, build and maintain strong client relationships, and lead the entire sales cycle from prospecting to closing deals.',
      '<b>Strategic Planning</b>: Develop and implement comprehensive business development strategies to achieve company growth objectives. Collaborate with the leadership team to set clear targets and KPIs.',
      '<b>Partnership Development</b>: Explore and establish strategic partnerships with other organizations, software vendors, and industry leaders to create mutually beneficial alliances.',
      '<b>Revenue Growth</b>: Drive revenue growth by identifying upsell and cross-sell opportunities within the existing client base and ensuring client satisfaction.',
      "<b>Proposal Development</b>: Prepare compelling proposals, presentations, and pitches tailored to clients' specific needs and requirements.",
      "<b>Networking</b>: Attend industry events, conferences, and trade shows to expand the company's network and foster new business relationships.",
      '<b>Team Collaboration</b>: Collaborate closely with the marketing, sales, and technical teams to align business development efforts with company goals.',
    ],
    requirements: [
      'Fluent in English, able to communicate directly with customers.',
      "Bachelor's degree in Business Administration, Marketing, or a related field.",
      'Proven track record of at least 3 in business development and strategy roles within the software consulting or IT industry.',
      'Strong understanding of software solutions, technologies, and consulting services.',
      'Exceptional communication, negotiation, and presentation skills.',
      'Strategic thinker with the ability to analyze data, make data-driven decisions, and adapt to market changes.',
      'Proficiency in CRM software and other sales tools.',
      'Self-motivated, results-oriented, and a team player.',
    ],
    offers: [
      'Competitive salary and performance-based bonuses.',
      'Opportunity to shape the growth and direction of a leading software consulting firm.',
      'A collaborative and innovative work environment.',
      'Ongoing professional development and growth opportunities.',
    ],
    aboutJob:
      "As a Business Development Executive at Spartan, you will play a pivotal role in shaping the company's growth by identifying new business opportunities, developing strategic partnerships, and ensuring the firm's continued success. You will be responsible for crafting and implementing business development strategies to expand our client base and enhance our market presence.",
    tag: JobTag['BIZ_DEVELOPMENT_EXECUTIVE'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['ALL_LEVEL'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '30/10/2023',
    slug: '/apply-job/business-development-executive',
  },
  {
    id: 'job-14',
    position: 'Marketing Manager - Software',
    responsibilities: [
      'Own the marketing strategy and execution, including but not limited to seeking new clients, content/SEO, SEM, brand identity, and community building.',
      "Sales enablement will be a large part of what you do – Partner with Product Management to communicate the Product's value proposition to the sales team. Develop the sales tools and training that support the selling process of the Product.",
      'Conduct market research, benchmarking, and consumer studies.',
      'Be responsible for the product marketing strategy with a multi-channel timeline and marketing content plan in collaboration with internal & external teams.',
      'Craft strong product messages and strategies uniquely suited for our channels based on a deep understanding of the market and competitive landscape.',
      'Work with the product and sales to improve the user experience and marketing metrics.',
    ],
    requirements: [
      '5+ years of global experience in technical product marketing or product management in enterprise software (US/EU/Canada market..).',
      '1+ years managing marketing teams in Software companies.',
      'Experience generating massive leads for new software products.',
      'Intimate and hands-on knowledge of marketing tools.',
      'Product-led growth knowledge & growth hacking mindset.',
      'Proven ability to effectively articulate and showcase technology for different use cases and to different types of audiences.',
      'Self-starter with excellent project management skills who truly enjoys working in a fast-paced, innovative software company.',
      'Strong critical thinking and problem-solving skills.',
      'Excellent command of written and spoken English.',
      'BSc/BA in IT, Marketing, Communications, or a similar field.',
    ],
    offers: [
      'Competitive salary and performance-based bonuses.',
      'Opportunity to shape the growth and direction of a leading software consulting firm.',
      'A collaborative and innovative work environment.',
      'Ongoing professional development and growth opportunities.',
    ],
    aboutJob:
      "Spartan is a software development startup with world-class engineers focusing on technology. We seek an experienced Marketing Manager to lead our marketing campaigns and expand our product and service presence in international markets (US, EU, Canada, etc.). You will collaborate closely with the Business Development and Product teams to develop and execute marketing strategies tailored to attract customers and enhance the company's branding. If you are a Marketing Manager with software experience, please read on.",
    tag: JobTag['MARKETING_MANAGER'],
    location: [Location['REMOTE'], Location['OFFICE']],
    experienceLevel: ExperienceLevel['ALL_LEVEL'],
    enrollmentStatus: [EnrollmentStatus['FULL_TIME']],
    createdAt: '30/10/2023',
    slug: '/apply-job/marketing-manager-software',
  },
];
