export { HomePage } from './HomePage';
export { AboutUsPage } from './AboutUsPage';
export { LifeSpartanPage } from './LifeSpartanPage';
export { InternshipPage } from './InternshipPage';
export { ReadyToJoinPage } from './ReadyToJoinPage';
export { ContactUsPage } from './ContactUsPage';
export { CaseStudyVoltaPage } from './CaseStudyVoltaPage';
export { CaseStudyPage } from './CaseStudyPage';
export { ServicesPage } from './ServicesPage';
