import { ISEOPages, EPages } from './types';

export const hostname = '';

const SEOPages: ISEOPages = {
  [EPages.HOME]: {
    title: 'c0x12c',
    description: 'c0x12c',
    keywords: 'c0x12c',
    metaImage: '',
    slug: '/',
  },
  [EPages.ABOUT_US]: {
    title: 'c0x12c - About Us',
    description: 'c0x12c - About Us',
    keywords: 'c0x12c, about us',
    metaImage: '',
    slug: '/about-us',
  },
  [EPages.CASE_STUDY]: {
    title: 'c0x12c - Case Study',
    description: 'c0x12c - Case Study',
    keywords: 'c0x12c, Case Study',
    metaImage: '',
    slug: '/case-study',
  },
  [EPages.CONTACT_US]: {
    title: 'c0x12c - Contact Us',
    description: 'c0x12c - Contact Us',
    keywords: 'c0x12c, Contact Us',
    metaImage: '',
    slug: '/contact-us',
  },
  [EPages.SERVICES]: {
    title: 'c0x12c - Services',
    description: 'c0x12c - Services',
    keywords: 'c0x12c, Services',
    metaImage: '',
    slug: '/services',
  },
  [EPages.SERVICES_WEB]: {
    title: 'c0x12c - Service Web Development',
    description: 'c0x12c - Service Web Development',
    keywords: 'c0x12c, Service Web Development',
    metaImage: '',
    slug: '/services/web-development',
  },
  [EPages.SERVICES_MOBILE]: {
    title: 'c0x12c - Service Mobile App',
    description: 'c0x12c - Service Mobile App',
    keywords: 'c0x12c, Service Mobile App',
    metaImage: '',
    slug: '/services/mobile-app',
  },
  [EPages.SERVICES_CLOUD]: {
    title: 'c0x12c - Service Cloud',
    description: 'c0x12c - Service Cloud',
    keywords: 'c0x12c, Service Cloud',
    metaImage: '',
    slug: '/services/cloud',
  },
  [EPages.SERVICES_BACKEND]: {
    title: 'c0x12c - Service Backend',
    description: 'c0x12c - Service Backend',
    keywords: 'c0x12c, Service Backend',
    metaImage: '',
    slug: '/services/backend',
  },
  [EPages.SERVICES_EMERGING]: {
    title: 'c0x12c - Service Emerging Technologies',
    description: 'c0x12c - Service Emerging Technologies',
    keywords: 'c0x12c, Service Emerging Technologies',
    metaImage: '',
    slug: '/services/emerging-technologies',
  },
  [EPages.CASE_STUDY_VOLTA]: {
    title: 'c0x12c - Case Study - Volta',
    description: 'c0x12c - Case Study - Volta',
    keywords: 'c0x12c, Case Study - Volta',
    metaImage: '',
    slug: '/case-study/volta',
  },
  [EPages.CASE_STUDY_AGORA]: {
    title: 'c0x12c - Case Study - Live Cast',
    description: 'c0x12c - Case Study - Live Cast',
    keywords: 'c0x12c, Case Study - Live Cast',
    metaImage: '',
    slug: '/case-study/live-cast',
  },
  [EPages.CASE_STUDY_URSA]: {
    title: 'c0x12c - Case Study - URSA Live',
    description: 'c0x12c - Case Study - URSA Live',
    keywords: 'c0x12c, Case Study - URSA Live',
    metaImage: '',
    slug: '/case-study/ursa',
  },
  [EPages.CASE_STUDY_HERU]: {
    title: 'c0x12c - Case Study - Heru',
    description: 'c0x12c - Case Study - Heru',
    keywords: 'c0x12c, Case Study - Heru',
    metaImage: '',
    slug: '/case-study/heru',
  },
  [EPages.LIFE_SPARTAN]: {
    title: 'c0x12c - Life of Spartan',
    description: 'c0x12c - Life of Spartan',
    keywords: 'c0x12c, Life of Spartan',
    metaImage: '',
    slug: '/life-spartan',
  },
  [EPages.INTERNSHIP]: {
    title: 'c0x12c - Internship program',
    description: 'c0x12c - Internship program',
    keywords: 'c0x12c, Internship program',
    metaImage: '',
    slug: '/internship-program',
  },
  [EPages.READY_TO_JOIN]: {
    title: 'c0x12c - Ready to join',
    description: 'c0x12c - Ready to join',
    keywords: 'c0x12c, Ready to join',
    metaImage: '',
    slug: '/ready-to-join',
  },
  [EPages.APPLY_JOB]: {
    title: 'c0x12c - Apply for job',
    description: 'c0x12c - Apply for job',
    keywords: 'c0x12c, Apply for job',
    metaImage: '',
    slug: '/apply-job',
  },
  [EPages.CASE_STUDY_LIQUIDITY]: {
    title: 'c0x12c - Case study - Liquidity',
    description: 'c0x12c - Case study - Liquidity',
    keywords: 'c0x12c,Case study - Liquidity',
    metaImage: '',
    slug: '/case-study/liquidity',
  },
  [EPages.CASE_STUDY_CF]: {
    title: 'c0x12c - Case study - ChargeFuze',
    description: 'c0x12c - Case study - ChargeFuze',
    keywords: 'c0x12c,Case study - ChargeFuze',
    metaImage: '',
    slug: '/case-study/chargefuze',
  },
};

export default SEOPages;
