name: Create Patch Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Bump version
        run: |
          git config --global user.email "github-actions@c0x12c.com"
          git config --global user.name "Github Actions"
          ./tools/create_release.sh patch
